@baseUrl = http://localhost:3000
@contentType = application/json
@authToken =
@userId =
@adminUserId =

### 1.1 Create a regular user
POST {{baseUrl}}/users/register
Content-Type: {{contentType}}

{
  "name": "Test User",
  "email": "test@example.com", 
  "password": "test123",
  "role": "USER"
}


### 1.2 Create an admin user
POST {{baseUrl}}/users/register
Content-Type: {{contentType}}

{
  "name": "Admin",
  "email": "admin@example.com",
  "password": "admin123",
  "role": "ADMIN"
}

### 2.1 Get user by ID
GET {{baseUrl}}/users/1