@baseUrl = http://localhost:3000
@contentType = application/json
@authToken =
@userId =
@adminUserId =

### 1.1 Create a regular user
POST {{baseUrl}}/users/register
Content-Type: {{contentType}}

{
  "name": "John Doe",
  "email": "john.doe@example.com",
  "password": "securePassword123",
  "role": "USER"
}


### 1.2 Create an admin user
POST {{baseUrl}}/users/register
Content-Type: {{contentType}}

{
  "name": "Admin",
  "email": "admin@example.com",
  "password": "admin123",
  "role": "ADMIN"
}